name: Test
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download sources
        uses: actions/checkout@v5
      - name: Set up NodeJS
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: ./package-lock.json
      - name: Install frontend dependencies
        run: |
          cd Prototypes/POC-Prototype1
          npm install
      - name: Generate sample
        run: |
          cd Prototypes/POC-Prototype1
          mkdir frontend/public
          npx --yes dummy-json src/data/sample_data.hbs > public/sample_data.json
      - name: Build frontend
        run: |
          cd Prototypes/POC-Prototype1
          npm run build
      - name: Start frontend
        run: |
          cd Prototypes/POC-Prototype1
          docker compose up --detach
      - name: Wait for frontend
        uses: docker://benel/wait-for-response:1
        with:
          args: http://localhost/ 200 30000 500
      - name: Watch frontend initial payload
        run: curl --silent localhost