name: Test
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download sources
        uses: actions/checkout@v5
      - name: Set up NodeJS
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: Prototypes/POC-Prototype1/package-lock.json
      - name: Install frontend dependencies
        run: |
          cd Prototypes/POC-Prototype1
          npm install
      - name: Generate sample
        run: |
          cd Prototypes/POC-Prototype1
          npx --yes dummy-json src/data/sample_data.hbs > public/sample_data.json
      - name: Build frontend
        run: |
          cd Prototypes/POC-Prototype1
          npm run build
      - name: Save frontend build for later
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: Prototypes/POC-Prototype1/dist
  measure_ecoindex:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download sources
        uses: actions/checkout@v5
      - name: Start application
        uses: ./.github/actions/start
      - name: Install GreenIT Analysis CLI
        run: |
          wget https://github.com/cnumr/GreenIT-Analysis-cli/archive/refs/heads/master.zip
          unzip master.zip
          cd GreenIT-Analysis-cli-master
          npm install
          npm link
      - name: Run GreenIT Analysis CLI
        run: |
          cd Prototypes/POC-Prototype1
          greenit analyse --format html --ci scenarios/scroll_post_feed.yml
      - name: Save results
        uses: actions/upload-artifact@v4
        with:
          name: EcoIndex
          path: Prototypes/POC-Prototype1/resultats_test_yml.html
          #path: Prototypes/POC-Prototype1/*.html

  measure_energy_consumption:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download sources
        uses: actions/checkout@v5
      - name: Start application
        uses: ./.github/actions/start
      - name: Install GreenFrame CLI
        run: |
          cd Prototypes/POC-Prototype1
          wget https://github.com/benel/greenframe-cli/archive/refs/heads/post-app.zip
          unzip post-app.zip
          cd greenframe-cli-post-app
          npm install -g corepack
          yarn
          yarn build 
      - name: Run GreenFrame CLI
        run: |
          cd Prototypes/POC-Prototype1
          ./greenframe-cli-post-app/bin/run analyze --config greenframe.yml > Consumption.txt
      - name: Save results
        uses: actions/upload-artifact@v4
        with:
          name: Consumption
          path: Prototypes/POC-Prototype1/Consumption.txt